import type { DiagnosticQuestion } from "./diagnostic-types";

export const DIAGNOSTIC_QUESTIONS: DiagnosticQuestion[] = [
  {
    id: 1,
    topic: "向量的模",
    topicTag: "vec_magnitude",
    level: "L1",
    kind: "mcq",
    stem: [
      { type: "text", value: "設 " },
      { type: "math", latex: "\\vec{a} = (3, -4)" },
      { type: "text", value: "，則 " },
      { type: "math", latex: "|\\vec{a}|" },
      { type: "text", value: " 的值為：" },
    ],
    options: [
      { key: "A", latex: "1" },
      { key: "B", latex: "7" },
      { key: "C", latex: "5" },
      { key: "D", latex: "\\sqrt{7}" },
    ],
    correctKey: "C",
  },
  {
    id: 2,
    topic: "向量加減法",
    topicTag: "vec_addition",
    level: "L1",
    kind: "mcq",
    stem: [
      { type: "text", value: "已知 " },
      { type: "math", latex: "\\vec{a} = (2, 1)" },
      { type: "text", value: "，" },
      { type: "math", latex: "\\vec{b} = (-1, 3)" },
      { type: "text", value: "，則 " },
      { type: "math", latex: "\\vec{a} - \\vec{b}" },
      { type: "text", value: " 等於：" },
    ],
    options: [
      { key: "A", latex: "(1, 4)" },
      { key: "B", latex: "(3, -2)" },
      { key: "C", latex: "(3, 2)" },
      { key: "D", latex: "(-3, 2)" },
    ],
    correctKey: "B",
  },
  {
    id: 3,
    topic: "數乘向量",
    topicTag: "scalar_mult",
    level: "L1",
    kind: "mcq",
    stem: [
      { type: "text", value: "設 " },
      { type: "math", latex: "\\vec{a} = (1, -2)" },
      { type: "text", value: "，則 " },
      { type: "math", latex: "3\\vec{a}" },
      { type: "text", value: " 等於：" },
    ],
    options: [
      { key: "A", latex: "(3, 6)" },
      { key: "B", latex: "(3, -6)" },
      { key: "C", latex: "(-3, 6)" },
      { key: "D", latex: "(1, -6)" },
    ],
    correctKey: "B",
  },
  {
    id: 4,
    topic: "向量共線條件",
    topicTag: "vec_collinear",
    level: "L2",
    kind: "mcq",
    stem: [
      { type: "text", value: "已知 " },
      { type: "math", latex: "\\vec{a} = (2, 3)" },
      { type: "text", value: "，" },
      { type: "math", latex: "\\vec{b} = (4, k)" },
      { type: "text", value: "，若 " },
      { type: "math", latex: "\\vec{a} \\parallel \\vec{b}" },
      { type: "text", value: "，則 " },
      { type: "math", latex: "k" },
      { type: "text", value: " = ？" },
    ],
    options: [
      { key: "A", latex: "3" },
      { key: "B", latex: "6" },
      { key: "C", latex: "8" },
      { key: "D", latex: "\\dfrac{3}{2}" },
    ],
    correctKey: "B",
  },
  {
    id: 5,
    topic: "數量積計算",
    topicTag: "dot_product",
    level: "L2",
    kind: "fill",
    stem: [
      { type: "text", value: "設 " },
      { type: "math", latex: "\\vec{a} = (3, 1)" },
      { type: "text", value: "，" },
      { type: "math", latex: "\\vec{b} = (2, -3)" },
      { type: "text", value: "，計算 " },
      { type: "math", latex: "\\vec{a} \\cdot \\vec{b}" },
      { type: "text", value: " =" },
    ],
    matchFill: (raw) => raw.replace(/\s/g, "") === "3",
    fillPlaceholder: "輸入數值",
  },
  {
    id: 6,
    topic: "向量夾角",
    topicTag: "vec_angle",
    level: "L2",
    kind: "mcq",
    stem: [
      { type: "text", value: "設 " },
      { type: "math", latex: "\\vec{a} = (1, \\sqrt{3})" },
      { type: "text", value: "，" },
      { type: "math", latex: "\\vec{b} = (2, 0)" },
      { type: "text", value: "，則 " },
      { type: "math", latex: "\\vec{a}" },
      { type: "text", value: " 與 " },
      { type: "math", latex: "\\vec{b}" },
      { type: "text", value: " 所成的角為：" },
    ],
    options: [
      { key: "A", latex: "30°" },
      { key: "B", latex: "45°" },
      { key: "C", latex: "60°" },
      { key: "D", latex: "90°" },
    ],
    correctKey: "C",
  },
  {
    id: 7,
    topic: "幾何中的向量表達",
    topicTag: "vec_geometry",
    level: "L2",
    kind: "mcq",
    stem: [
      { type: "text", value: "△ABC 中，M 為 BC 的中點，" },
      { type: "math", latex: "\\overrightarrow{AB} = \\vec{a}" },
      { type: "text", value: "，" },
      { type: "math", latex: "\\overrightarrow{AC} = \\vec{b}" },
      { type: "text", value: "，則 " },
      { type: "math", latex: "\\overrightarrow{AM}" },
      { type: "text", value: " =" },
    ],
    options: [
      { key: "A", latex: "\\vec{a} + \\vec{b}" },
      { key: "B", latex: "\\dfrac{\\vec{a} + \\vec{b}}{2}" },
      { key: "C", latex: "\\dfrac{\\vec{b} - \\vec{a}}{2}" },
      { key: "D", latex: "\\vec{a} - \\vec{b}" },
    ],
    correctKey: "B",
  },
  {
    id: 8,
    topic: "綜合（模 + 積 + 角）",
    topicTag: "synthesis",
    level: "L3",
    kind: "fill",
    stem: [
      { type: "text", value: "已知 " },
      { type: "math", latex: "|\\vec{a}| = \\sqrt{2}" },
      { type: "text", value: "，" },
      { type: "math", latex: "|\\vec{b}| = \\sqrt{6}" },
      { type: "text", value: "，" },
      { type: "math", latex: "\\vec{a} \\cdot \\vec{b} = \\sqrt{3}" },
      { type: "text", value: "，求 " },
      { type: "math", latex: "\\vec{a}" },
      { type: "text", value: " 與 " },
      { type: "math", latex: "\\vec{b}" },
      { type: "text", value: " 所成角 " },
      { type: "math", latex: "\\theta" },
      { type: "text", value: "。（可寫計算過程或最終答案）" },
    ],
    matchFill: (raw) => {
      const t = raw.trim();
      if (/\b160\b|\b360\b/.test(t)) return false;
      return (
        /60\s*°|60度/u.test(t) ||
        (/\b60\b/.test(t) && /θ|theta|角/u.test(t)) ||
        /[=＝]\s*60(?:\s*°|\s*度)?/u.test(t) ||
        /π\s*\/\s*3|pi\s*\/\s*3/u.test(t.toLowerCase())
      );
    },
    fillPlaceholder: "例如：60° 或簡要過程",
    fillRows: 4,
  },
];
